# Generated by Django 5.0.7 on 2024-07-09 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_nickname', models.CharField(default='', max_length=100)),
                ('user_name', models.CharField(default='', max_length=100)),
                ('user_gender', models.CharField(default='', max_length=100)),
                ('user_age', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
