# Generated by Django 5.0.7 on 2024-07-09 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='user_gender',
            new_name='age',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_age',
            new_name='gender',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='user_nickname',
            new_name='nickname',
        ),
    ]
