# Generated by Django 5.0.7 on 2024-07-09 23:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_rest', '0002_rename_user_gender_user_age_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='age',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='name',
        ),
    ]
